- name: create /etc/tuned/no-thp directory
  file:
    path: /etc/tuned/no-thp
    state: directory
    mode: 0755

- name: configure /etc/tuned/no-thp/tuned.conf
  template:
    src:  ../templates/tuned.conf.j2
    dest: /etc/tuned/no-thp/tuned.conf
    owner: root
    group: root
    mode: '0655'
  register: tuned_conf

- name: tuned-adm profile no-thp
  shell: tuned-adm profile no-thp
  when: tuned_conf.changed
